### ISSUE TITLE
This authorization code has been used ??

### ISSUE THREAD

**Issue by curruwilla** [espresso-dev/instagram-basic-display-php#14]
Hi,

I have a problem generating the long term acess_token of instagram basic api.
The message is returning:

{
    "error_type": "OAuthException",
    "code": 400,
    "error_message": "This authorization code has been used"
}

How can I solve this?

**Comment by hermanschutte** [comment]
Hi @curruwilla,

Could you include an example of how you are retrieving the auth code, and how you are trying to exchange it?

**Comment by curruwilla** [comment]
> Hi @curruwilla,
> 
> Could you include an example of how you are retrieving the auth code, and how you are trying to exchange it?

Hi @hermanespresso 

I'm using it exactly as it is in the repository documentation:

> $code = $_GET['code'];
$token = $instagram->getOAuthToken($code, true);
$token = $instagram->getLongLivedToken($token, true);

However, in the **'getOAuthToken'** method, this error message is returned, which even if I use the second parameter to return only the acess_token, the undefined error.

I'm doing more tests, if you discover something, please share it here

**Comment by hermanschutte** [comment]
@curruwilla are you still experiencing this issue happening?

**Comment by curruwilla** [comment]
> @curruwilla are you still experiencing this issue happening?

Nope, thanks

**Comment by Influish** [comment]
I am facing the same issue, how did you fixed it @curruwilla 

> > [@curruwilla](https://github.com/curruwilla) are you still experiencing this issue happening?
> 
> Nope, thanks
