### ISSUE TITLE
Displaying Hashtags

### ISSUE THREAD

**Issue by adambichler** [espresso-dev/instagram-basic-display-php#6]
I found a Stackoverflow question where it mentions displaying hashtags using this plugin.
(see here: https://stackoverflow.com/questions/60180959/with-the-instagram-api-changes-in-march-2020-whats-the-easiest-way-to-embed-a?newreg=19bbfc33ea05450dabe0b2e9c0e19122)

How would you accomplish that?
Thanks!

**Comment by hermanschutte** [comment]
You will only be able to display your own hashtagged photos unless you use the Graph API.
